### ISSUE TITLE
ScaleFast MutatorLib?

### ISSUE THREAD

**Issue by FosterType** [roboDocs/Robofont-scripts#3]
It might've just been me because I'm a noob at GitHub but when I downloaded the top level folder, ScaleFast wasn't working for me. When I opened the Extension, the contents of the mutatorScaleLib were missing. When I downloaded those files manually and inserted them, it worked.

**Comment by gferreira** [comment]
hello Dave, thanks for the note. (it was still a work in progress)

mutatorScale is now included as a git submodule.

the latest version of ScaleFast is now here: [roboDocs/ScaleFast](https://github.com/roboDocs/ScaleFast)
